export const CONDITIONS: {[key: string]: string} = {
    "swarm-yes": "During a swarm",
    "swarm-no": "Not during a swarm",
    "time-morning": "In the morning",
    "time-day": "During the day",
    "time-night": "At night",
    "radar-on": "Using PokéRadar",
    "radar-off": "Not using PokéRadar",
    "slot2-none": "No game in slot 2",
    "slot2-ruby": "Ruby in slot 2",
    "slot2-sapphire": "Sapphire in slot 2",
    "slot2-emerald": "Emerald in slot 2",
    "slot2-firered": "FireRed in slot 2",
    "slot2-leafgreen": "LeafGreen in slot 2",
    "radio-off": "Radio off",
    "radio-hoenn": "Hoenn radio",
    "radio-sinnoh": "Sinnoh radio",
    "season-spring": "During Spring",
    "season-summer": "During Summer",
    "season-autumn": "During Autumn",
    "season-winter": "During Winter",
    "starter-bulbasaur": "Bulbasaur as starter",
    "starter-squirtle": "Squirtle as starter",
    "starter-charmander": "Charmander as starter",
    "starter-chespin": "Chespin as starter",
    "starter-fennekin": "Fennekin as starter",
    "starter-froakie": "Froakie as starter",
    "tv-option-blue": "Chose ‘Blue’ on the TV news report",
    "tv-option-red": "Chose ‘Red’ on the TV news report",
    "story-progress-awakened-beasts": "Awakened the legendary beasts at Burned Tower",
    "story-progress-beat-galactic-coronet": "Visited Lake Verity after defeating Team Galactic at Mt. Coronet",
    "story-progress-oak-eterna-city": "Talked to Professor Oak at Eterna City",
    "story-progress-vermilion-copycat": "Visited the Pokémon Fan Club with Copycat’s doll",
    "story-progress-met-tornadus-thundurus": "Met Tornadus or Thundurus in a cutscene",
    "story-progress-beat-elite-four-round-two": "Beat the Elite 4 for the second time",
    "story-progress-hall-of-fame": "Enter the Hall of Fame",
    "story-progress-none": "None",
    "story-progress-national-dex": "Acquired National Pokédex",
    "other-none": "None",
    "other-snorlax-11-beat-league": "Beat the Pokémon league after knocking out Snorlax at Route 11",
    "other-virtual-console": "Playing on the Virtual Console Release",
    "story-progress-cure-eldritch-nightmares": "Cure the nightmares of Eldritch’s Son",
    "other-talk-to-cynthias-grandmother": "Talk to Cynthia’s grandmother",
    "item-none": "No item requirement",
    "item-adamant-orb": "Have Adamant Orb in bag",
    "item-lustrous-orb": "Have Lustrous Orb in bag",
    "item-helix-fossil": "Have Helix Fossil in bag",
    "item-dome-fossil": "Have Dome Fossil in bag",
    "item-old-amber": "Have Old Amber in bag",
    "item-root-fossil": "Have Root Fossil in bag",
    "item-claw-fossil": "Have Claw Fossil in bag",
    "story-progress-defeat-jupiter": "Defeat Jupiter",
    "story-progress-beat-team-galactic-iron-island": "Defeat Team Galactic at Iron Island",
    "other-correct-password": "Input correct password",
    "story-progress-zephyr-badge": "Obtained Zephyr badge",
    "story-progress-beat-red": "Defeat Red",
    "other-received-kanto-starter": "Received a Kanto Starter",
    "story-progress-receive-tm-from-claire": "Received TM59 From Claire",
    "other-regirock-regice-registeel-in-party": "Have Regirock, Regice and Registeel in the party",
    "weekday-sunday": "Sunday",
    "weekday-monday": "Monday",
    "weekday-tuesday": "Tuesday",
    "weekday-wednesday": "Wednesday",
    "weekday-thursday": "Thursday",
    "weekday-friday": "Friday",
    "weekday-saturday": "Saturday",
    "first-party-pokemon-high-friendship": "The first Pokémon in the player’s party has a high friendship stat",
    "story-progress-defeat-mars": "Beat Mars for the first time",
    "item-odd-keystone": "Have Odd Keystone in bag",
    "other-talked-to-32-people-underground": "Has talked to at least 32 people in the underground",
    "story-progress-returned-machine-part": "Returned Machine Part to Power Plant",
    "other-event-arceus-in-party": "Have an Event Arceus in the party"
}